version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  go: "1.25"

linters:
  default: standard

formatters:
  enable:
    - gofmt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
